name: Tag Release

on:
  pull_request:
    types: [closed]

jobs:
  release:
    uses: clouddrove-sandbox/github-shared-workflows/.github/workflows/tag-release.yml@feat/tag-release
    with:
      target_branch: master
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
