name: Tag Release
permissions: write-all  

on:
  pull_request:
    types: [closed]

jobs:
  release:
    uses: clouddrove-sandbox/terraform-azure-vnt/.github/workflows/workflow.yml@master
    with:
      target_branch: master
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GITHUB: ${{ secrets.GITHUB }}
